#16 & #17 resolved
rzmk/mega-todo pull request #19
Opened 2022-01-06 04:46 UTC by ishaanbedi

Changed the alignment from CSS file and made the class name embed in the dataset

2022-01-06 13:27 UTC, rzmk requested changes
Great work! I've added some changes to make things cleaner and easier to understand, so commit these and this should be good to go! 🚀

2022-01-06 13:27 UTC, rzmk commented on index.html
> +                <datalist id="citynames" class="DataList">
Semantically better. Commit this along with the below Javascript commit. 
```suggestion
                <input list="classes" class="className">
                <datalist id="classes" class="DataList">
```

2022-01-06 13:27 UTC, rzmk commented on js/script.js
> +        document.querySelector("#citynames").appendChild(ele);
Commit this along with the above in `index.html`.
```suggestion
        document.querySelector("#classes").appendChild(ele);
```

2022-01-06 14:14 UTC, ishaanbedi commented
Hey! I've edited the required code.

2022-01-06 15:14 UTC, rzmk commented
@ishaanbedi Looks great!

One issue I find is that if you select a class and insert, it'll add another copy of it. Would you like to try checking against the classes on insert and make the class addition conditional?

Example:

![image](https://user-images.githubusercontent.com/30333942/148404867-f1c1b38c-9ce2-4010-8958-95589a55f822.png)

2022-01-07 03:31 UTC, ishaanbedi commented
Alright! Working on it

2022-01-07 04:14 UTC, ishaanbedi commented
Hi! I've fixed it!

2022-01-07 14:03 UTC, rzmk requested changes

2022-01-07 14:03 UTC, rzmk commented on js/script.js
> +            var ele = document.createElement("OPTION"); var ele = document.createElement("OPTION");
Curious why there's a declaration of `ele` twice.

2022-01-07 14:09 UTC, ishaanbedi commented on js/script.js
> +            var ele = document.createElement("OPTION"); var ele = document.createElement("OPTION");
Might have been by mistake! 
Corrected it

2022-01-07 14:55 UTC, rzmk approved these changes
Good to go! 🚀
Great work once again! 😁

2022-01-07 14:55 UTC, merged